"""Typer entry point for the bffi-pipeline CLI. Stages are wired up here."""

from __future__ import annotations

import atexit as _atexit
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import TYPE_CHECKING, Annotated

if TYPE_CHECKING:
    from bffi_pipeline.run_manifest import DiscoveredRun

import httpx
import typer

from bffi_pipeline import status as status_module
from bffi_pipeline.config import Settings, get_settings
from bffi_pipeline.eval import embed_benchmark
from bffi_pipeline.eval import grow as eval_grow
from bffi_pipeline.eval import harness as eval_harness
from bffi_pipeline.provenance import writer as prov_writer
from bffi_pipeline.stages import (
    bf_to_bffi,
    embeddings,
    judge,
    load,
    load_finto,
    local_concept_resolver,
    marc_to_bf,
    merge,
    reconcile,
    skosify_run,
    workkey,
    ysa_disambiguation_report,
)
from bffi_pipeline.stages.observability import (
    StageEventEmitter,
    set_active_emitter,
)


def _init_observability(settings: Settings) -> StageEventEmitter | None:
    """Construct + register the per-invocation StageEventEmitter (P-11 Phase A).

    Resolves ``settings.observability_sidecar`` and
    ``settings.run_uuid`` into a configured :class:`StageEventEmitter`
    and parks it as the process-wide active emitter so any
    pipeline-stage call can emit without function-signature plumbing.

    ``observability_sidecar`` resolution:
    - empty (default): ``<data_dir>/stage-events.jsonl``.
    - ``"none"`` or ``"/dev/null"`` (case-insensitive): stderr-only,
      no JSONL append.
    - any other value: treated as a path.

    ``run_uuid`` resolution:
    - empty (default): a fresh ``uuid4().hex`` per invocation.
    - any other value: pinned (operator-controlled, useful for
      replay).
    """
    sidecar_str = settings.observability_sidecar.strip()
    sidecar_path: Path | None
    if not sidecar_str:
        sidecar_path = settings.data_dir / "stage-events.jsonl"
    elif sidecar_str.lower() in {"none", "/dev/null", "off"}:
        sidecar_path = None
    else:
        sidecar_path = Path(sidecar_str)

    # P-32 Phase E: ``run_uuid`` is generated by ``Settings._resolve_run_identity``
    # at construction time (so ``data_dir`` resolution can use it). Read
    # it back here for emitter wiring + startup-log echo.
    run_uuid = settings.run_uuid

    # P-32 Phase A: write the initial bffi-run.json manifest into
    # ``data_dir``. Skipped when the operator has explicitly disabled
    # the sidecar (BFFI_OBSERVABILITY_SIDECAR=none) — same opt-out
    # axis. Tests that need a no-manifest emitter construct one
    # directly without going through ``_init_observability``.
    manifest_path: Path | None = None
    if sidecar_path is not None:
        from bffi_pipeline.run_manifest import (
            mark_run_complete as _mark_run_complete,
        )
        from bffi_pipeline.run_manifest import (
            write_initial_manifest,
        )

        manifest_path = write_initial_manifest(
            settings.data_dir,
            run_uuid=run_uuid,
            description=settings.run_description,
            pipeline_git_sha=_resolve_git_sha(),
        )
        # ``atexit`` stamps ``ended_at`` + ``status="completed"`` when
        # Python shuts down normally. A crash / SIGKILL leaves the
        # manifest at ``status="running"``; the operator clears it via
        # ``bffi-pipeline runs mark-complete <uuid> --status=aborted``.
        _atexit.register(_mark_run_complete, settings.data_dir, "completed")

    emitter = StageEventEmitter(
        sidecar_path=sidecar_path,
        run_uuid=run_uuid,
        manifest_path=manifest_path,
    )
    set_active_emitter(emitter)
    # Echo the active run_uuid so operators inspecting a fresh invocation
    # (especially direct ``bffi-pipeline <subcmd>`` calls that bypass the
    # runner scripts) know which run to pick from Grafana's
    # ``$active_run`` dropdown. Stderr so it stays out of any stdout
    # capture / pipe consumers.
    typer.echo(f"[bffi-pipeline] BFFI_RUN_UUID={run_uuid}", err=True)
    # P-32 Phase E: echo the resolved ``data_dir`` with a
    # canonical-vs-override marker so the operator can spot the
    # ``BFFI_DATA_DIR`` escape-hatch case at a glance. "canonical"
    # means the dir was derived from ``runs_root / run_uuid`` (the new
    # default); "override" means the operator set ``BFFI_DATA_DIR``
    # explicitly and the run won't show up in ``bffi-pipeline runs
    # list`` unless they ``adopt`` it.
    if "data_dir" in settings.model_fields_set:
        typer.echo(
            f"[bffi-pipeline] data_dir={settings.data_dir} (override via BFFI_DATA_DIR — "
            f"non-canonical; runs list / prune will not see this run unless you adopt it)",
            err=True,
        )
    else:
        typer.echo(
            f"[bffi-pipeline] data_dir={settings.data_dir} (canonical)",
            err=True,
        )
    return emitter


def _resolve_git_sha() -> str | None:
    """Return the current HEAD SHA, or ``None`` if not in a git checkout.

    Best-effort: shells out to ``git rev-parse HEAD``. Used by P-32
    Phase A to stamp the pipeline-version field on the run manifest.
    """
    import subprocess

    repo_root = Path(__file__).resolve().parent.parent
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=repo_root,
            capture_output=True,
            check=True,
            text=True,
            timeout=2.0,
        )
    except (subprocess.SubprocessError, FileNotFoundError, OSError):
        return None
    sha = result.stdout.strip()
    return sha or None


app = typer.Typer(help="BFFI pipeline CLI.", no_args_is_help=True)
provenance_app = typer.Typer(help="Provenance graph maintenance (M7).", no_args_is_help=True)
app.add_typer(provenance_app, name="provenance")
runs_app = typer.Typer(
    help="Run lifecycle management (P-32). List, prune, tag, migrate runs under BFFI_RUNS_ROOT.",
    no_args_is_help=True,
)
app.add_typer(runs_app, name="runs")


_RUNS_LIST_SORT_KEYS = ("started", "ended", "size", "run_uuid")
_RUNS_LIST_DEFAULT_LIMIT = 50


@runs_app.command("list")
def runs_list_command(
    sort: Annotated[
        str,
        typer.Option(
            "--sort",
            help=(
                "Sort key. One of: started, ended, size, run_uuid. "
                "Default: started (descending — newest first)."
            ),
        ),
    ] = "started",
    status_filter: Annotated[
        str | None,
        typer.Option(
            "--status",
            help=(
                "Comma-separated status filter (e.g. 'completed,running'). "
                "Defaults to no status filter."
            ),
        ),
    ] = None,
    tag: Annotated[
        list[str] | None,
        typer.Option(
            "--tag",
            help="Tag filter; repeatable for AND semantics. Defaults to no tag filter.",
        ),
    ] = None,
    older_than: Annotated[
        str | None,
        typer.Option(
            "--older-than",
            help=(
                "Select runs whose started_at is older than this duration. "
                "Format: NN<unit>; unit in d/w/mo/y (e.g. 30d, 2w, 6mo, 1y)."
            ),
        ),
    ] = None,
    limit: Annotated[
        int,
        typer.Option(
            "--limit",
            help="Maximum rows to render after sort. Default: 50.",
        ),
    ] = _RUNS_LIST_DEFAULT_LIMIT,
    include_legacy: Annotated[
        bool,
        typer.Option(
            "--include-legacy",
            help=(
                "Include directories under BFFI_RUNS_ROOT that lack a "
                "bffi-run.json. They render with synthesised "
                "run_uuid='legacy-<sha1>' and status='unknown'."
            ),
        ),
    ] = False,
    json_output: Annotated[
        bool,
        typer.Option(
            "--json",
            help="Emit JSON array (one object per run) to stdout instead of a table.",
        ),
    ] = False,
    tsv_output: Annotated[
        bool,
        typer.Option(
            "--tsv",
            help="Emit tab-separated rows to stdout instead of a table.",
        ),
    ] = False,
    verbose: Annotated[
        bool,
        typer.Option(
            "--verbose",
            "-v",
            help="Show full started_at ISO timestamp (relative-time hint dropped).",
        ),
    ] = False,
) -> None:
    """List runs under ``BFFI_RUNS_ROOT`` with sort + filter + format options.

    P-32 Phase B. Default rendering is a plain-text table tailored for
    operator terminal width; ``--json`` / ``--tsv`` produce machine-
    consumable output. Legacy dirs (no manifest) are skipped by default
    so the table reflects the canonical run set; pass
    ``--include-legacy`` to see them too.
    """
    from bffi_pipeline.run_manifest import (
        compute_dir_size,
        discover_legacy_dirs,
        discover_runs,
    )

    if sort not in _RUNS_LIST_SORT_KEYS:
        typer.echo(
            f"Invalid --sort={sort!r}; expected one of: {', '.join(_RUNS_LIST_SORT_KEYS)}.",
            err=True,
        )
        raise typer.Exit(code=2)
    if json_output and tsv_output:
        typer.echo("--json and --tsv are mutually exclusive.", err=True)
        raise typer.Exit(code=2)

    older_than_td, statuses, tags = _parse_prune_filters(older_than, status_filter, tag)

    settings = get_settings()
    typer.echo(f"[bffi-pipeline] BFFI_RUNS_ROOT={settings.runs_root}", err=True)

    runs = list(discover_runs(settings.runs_root))
    if include_legacy:
        runs.extend(discover_legacy_dirs(settings.runs_root))

    filtered = _filter_runs_for_listing(
        runs,
        older_than=older_than_td,
        statuses=statuses,
        tags=tags,
    )

    sized: list[tuple[DiscoveredRun, int]] = [(run, compute_dir_size(run.path)) for run in filtered]
    sorted_rows = _sort_runs_for_listing(sized, sort_key=sort)
    truncated_rows = sorted_rows[:limit] if limit > 0 else sorted_rows

    if json_output:
        _render_runs_list_json(truncated_rows)
    elif tsv_output:
        _render_runs_list_tsv(truncated_rows)
    else:
        _render_runs_list_table(
            truncated_rows,
            total_matching=len(sorted_rows),
            verbose=verbose,
            runs_root=settings.runs_root,
        )


@runs_app.command("mark-complete")
def runs_mark_complete_command(
    run_uuid: Annotated[
        str,
        typer.Argument(
            help=(
                "The run_uuid (or a unique prefix) of the run to stamp. "
                "Resolved against BFFI_RUNS_ROOT/<run_uuid>/."
            ),
        ),
    ],
    status: Annotated[
        str,
        typer.Option(
            "--status",
            help=(
                "Status to write. One of: completed, aborted. "
                "Defaults to completed for the manual-completion case."
            ),
        ),
    ] = "completed",
) -> None:
    """Stamp ``ended_at`` + ``status`` on a run's manifest manually.

    Use when the pipeline crashed before the atexit hook fired and
    the manifest is stuck at ``status="running"``. The run dir is
    looked up under ``BFFI_RUNS_ROOT/<run_uuid>``; a unique prefix
    resolves to a single match.
    """
    from typing import cast

    from bffi_pipeline.run_manifest import RunStatus, mark_run_complete

    if status not in ("completed", "aborted"):
        typer.echo(
            f"Invalid --status={status!r}; expected one of: completed, aborted.",
            err=True,
        )
        raise typer.Exit(code=2)

    settings = get_settings()
    runs_root = settings.runs_root
    if not runs_root.is_dir():
        typer.echo(f"BFFI_RUNS_ROOT does not exist: {runs_root}", err=True)
        raise typer.Exit(code=2)

    matches = sorted(d for d in runs_root.iterdir() if d.is_dir() and d.name.startswith(run_uuid))
    if not matches:
        typer.echo(f"No run dir under {runs_root} matches prefix {run_uuid!r}.", err=True)
        raise typer.Exit(code=1)
    if len(matches) > 1:
        names = ", ".join(d.name for d in matches)
        typer.echo(
            f"Ambiguous run_uuid prefix {run_uuid!r}; matches: {names}",
            err=True,
        )
        raise typer.Exit(code=1)

    data_dir = matches[0]
    # ``status`` validated against the literal set above; cast is safe.
    mark_run_complete(data_dir, status=cast("RunStatus", status))
    typer.echo(f"Marked {data_dir.name} as status={status}.")


@runs_app.command("clear-fuseki")
def runs_clear_fuseki_command(
    apply: Annotated[
        bool,
        typer.Option(
            "--apply",
            help="Actually drop the graphs. Default is dry-run (preview only).",
        ),
    ] = False,
    verbose: Annotated[
        bool,
        typer.Option(
            "--verbose",
            "-v",
            help="Show per-graph URI + triple count + namespace classification.",
        ),
    ] = False,
    force_clear: Annotated[
        bool,
        typer.Option(
            "--force-clear",
            help=(
                "Bypass the BFFI_FUSEKI_CLEAR_MAX_TRIPLES safety threshold. "
                "Required when an oversized graph (e.g. a misconfigured "
                "settings.graph_base prefix-matching a vocabulary URI) needs "
                "to be dropped anyway."
            ),
        ),
    ] = False,
) -> None:
    """Manually drop every Fuseki named graph under ``settings.graph_base``.

    P-32 Phase H. Useful as a diagnostic ("what's in Fuseki right
    now?") and as a recovery action ("wipe Fuseki to a known-clean
    state; let the next ``bffi-pipeline load`` rebuild from
    canonical-skosified.ttl"). Vocabulary graphs (YSO, KANTO,
    allars, SLM, MUSO) live in their own URI namespaces outside
    ``graph_base`` and are NOT touched.
    """
    from bffi_pipeline.stages.fuseki_clear import clear_run_output_graphs

    settings = get_settings()
    auth: tuple[str, str] | None = (
        (settings.fuseki_user, settings.fuseki_password)
        if settings.fuseki_user and settings.fuseki_password
        else None
    )
    with httpx.Client(timeout=30.0, auth=auth) as client:
        result = clear_run_output_graphs(
            fuseki_url=settings.fuseki_url,
            graph_base=settings.graph_base,
            max_triples_per_graph=settings.fuseki_clear_max_triples,
            dry_run=not apply,
            force=force_clear,
            client=client,
        )

    if not result.fuseki_reachable:
        typer.echo(
            f"Fuseki unreachable at {settings.fuseki_url}; nothing cleared.",
            err=True,
        )
        raise typer.Exit(code=1)

    verb = "would drop" if not apply else "dropped"
    typer.echo(f"{verb} {len(result.dropped_graphs)} graph(s) under {settings.graph_base}:")
    for graph_uri in result.dropped_graphs:
        if verbose:
            typer.echo(f"  {graph_uri}")
        else:
            typer.echo(f"  {graph_uri.removeprefix(settings.graph_base)}")
    if result.skipped_oversized:
        typer.echo(
            f"\nSkipped {len(result.skipped_oversized)} oversized graph(s) "
            f"(> {settings.fuseki_clear_max_triples:,} triples; "
            f"pass --force-clear to drop):"
        )
        for graph_uri, n in result.skipped_oversized:
            typer.echo(f"  {graph_uri}  ({n:,} triples)")
    typer.echo(f"\nTotal triples surveyed: {result.total_triples_before:,}")
    if not apply:
        typer.echo("\n(--dry-run is the default; pass --apply to drop.)")


@runs_app.command("prune")
def runs_prune_command(
    older_than: Annotated[
        str | None,
        typer.Option(
            "--older-than",
            help=(
                "Select runs whose started_at is older than this duration. "
                "Format: NN<unit>; unit in d/w/mo/y (e.g. 30d, 2w, 6mo, 1y)."
            ),
        ),
    ] = None,
    status_filter: Annotated[
        str | None,
        typer.Option(
            "--status",
            help=(
                "Comma-separated status filter (e.g. 'completed,aborted'). "
                "Defaults to no status filter."
            ),
        ),
    ] = None,
    tag: Annotated[
        list[str] | None,
        typer.Option(
            "--tag",
            help="Tag filter; repeatable for AND semantics. Defaults to no tag filter.",
        ),
    ] = None,
    keep_last: Annotated[
        int | None,
        typer.Option(
            "--keep-last",
            help="Preserve the N most-recent runs (by started_at) regardless of filters.",
        ),
    ] = None,
    keep_tagged: Annotated[
        bool,
        typer.Option(
            "--keep-tagged",
            help="Preserve runs with at least one tag.",
        ),
    ] = False,
    apply: Annotated[
        bool,
        typer.Option(
            "--apply",
            help=(
                "Actually delete the selected dirs. Default is dry-run (preview only). "
                "Requires at least one filter that excludes some runs."
            ),
        ),
    ] = False,
    reset_exporter: Annotated[
        bool,
        typer.Option(
            "--reset-exporter",
            help=(
                "On --apply, also SIGTERM and relaunch the metrics exporter to drop "
                "stale in-memory Prometheus series. Reads PID from "
                "<BFFI_RUNS_ROOT>/.exporter.pid."
            ),
        ),
    ] = False,
    no_relaunch_exporter: Annotated[
        bool,
        typer.Option(
            "--no-relaunch-exporter",
            help=(
                "Pair with --reset-exporter to SIGTERM-without-relaunch; operator "
                "restarts `bffi-pipeline serve-metrics` themselves. Default is "
                "relaunch from the recorded argv."
            ),
        ),
    ] = False,
    reset_prometheus: Annotated[
        bool,
        typer.Option(
            "--reset-prometheus",
            help=(
                "On --apply, also call the Prometheus admin API to delete the pruned "
                "run_uuids' series from TSDB (Phase G — currently logs a warning, no-op)."
            ),
        ),
    ] = False,
    reset_fuseki: Annotated[
        bool,
        typer.Option(
            "--reset-fuseki",
            help=(
                "On --apply, also DROP <graph_base>* named graphs from Fuseki "
                "(Phase H — currently logs a warning, no-op)."
            ),
        ),
    ] = False,
    reset_all: Annotated[
        bool,
        typer.Option(
            "--reset-all",
            help="Shorthand for --reset-exporter + --reset-prometheus + --reset-fuseki.",
        ),
    ] = False,
) -> None:
    """Delete run dirs under ``BFFI_RUNS_ROOT`` matching the filters.

    ``--dry-run`` is the default: the command prints what *would* be
    deleted with sizes and totals, then exits without touching disk.
    Pass ``--apply`` to actually delete; at least one filter that
    excludes some runs (``--older-than``, ``--status``, ``--tag``,
    ``--keep-last``, ``--keep-tagged``) must be set to refuse the
    accidental "delete everything" case.

    Reset flags are accepted today as plumbing for Phases G + H; they
    log warnings and no-op until those phases ship.
    """
    from bffi_pipeline.run_manifest import discover_runs, select_for_pruning

    older_than_td, statuses, tags = _parse_prune_filters(older_than, status_filter, tag)
    has_filter = bool(older_than_td or statuses or tags or keep_last or keep_tagged)
    if apply and not has_filter:
        typer.echo(
            "--apply requires at least one filter that excludes some runs "
            "(--older-than / --status / --tag / --keep-last / --keep-tagged). "
            "Refusing to delete every run; "
            "pass a filter or run without --apply for a dry preview.",
            err=True,
        )
        raise typer.Exit(code=2)

    if reset_all:
        reset_exporter = True
        reset_prometheus = True
        reset_fuseki = True

    settings = get_settings()
    runs = discover_runs(settings.runs_root)
    if not runs:
        typer.echo(f"No runs found under {settings.runs_root}.")
        return

    to_delete, preserved = select_for_pruning(
        runs,
        older_than=older_than_td,
        statuses=statuses,
        tags=tags,
        keep_last=keep_last,
        keep_tagged=keep_tagged,
    )
    if not to_delete:
        typer.echo(f"No runs match the filters. (Discovered {len(runs)} total.)")
        return

    sized, total_bytes = _render_prune_preflight(to_delete, preserved, runs_root=settings.runs_root)

    if not apply:
        typer.echo("\n(--dry-run is the default; pass --apply to delete.)")
        return

    deleted_uuids = _execute_prune(sized, total_bytes)
    _maybe_invoke_resets(
        deleted_uuids,
        reset_exporter=reset_exporter,
        reset_prometheus=reset_prometheus,
        reset_fuseki=reset_fuseki,
        relaunch_exporter=not no_relaunch_exporter,
    )


def _parse_prune_filters(
    older_than: str | None,
    status_filter: str | None,
    tag: list[str] | None,
) -> tuple[timedelta | None, list[str] | None, list[str] | None]:
    """Parse the operator-supplied prune filters into typed values."""
    from bffi_pipeline.run_manifest import parse_duration

    older_than_td = None
    if older_than:
        try:
            older_than_td = parse_duration(older_than)
        except ValueError as exc:
            typer.echo(str(exc), err=True)
            raise typer.Exit(code=2) from exc

    statuses = None
    if status_filter:
        statuses = [s.strip() for s in status_filter.split(",") if s.strip()]

    tags = list(tag) if tag else None
    return older_than_td, statuses, tags


def _render_prune_preflight(
    to_delete: list[DiscoveredRun],
    preserved: list[DiscoveredRun],
    *,
    runs_root: Path,
) -> tuple[list[tuple[DiscoveredRun, int]], int]:
    """Render the dry-run / pre-apply preview; return (sized rows, total bytes)."""
    from bffi_pipeline.run_manifest import compute_dir_size

    typer.echo(f"Pruning {len(to_delete)} run(s) under {runs_root}:")
    sized: list[tuple[DiscoveredRun, int]] = []
    total_bytes = 0
    for run in to_delete:
        size = compute_dir_size(run.path)
        total_bytes += size
        sized.append((run, size))
        typer.echo(
            f"  {run.manifest.run_uuid[:12]}... "
            f"started={run.manifest.started_at.isoformat()} "
            f"status={run.manifest.status} "
            f"size={_human_bytes(size)}  "
            f"({run.manifest.description or '—'})"
        )
    typer.echo(f"Total to free: {_human_bytes(total_bytes)}")

    if preserved:
        typer.echo(f"\nPreserved by --keep-tagged / --keep-last ({len(preserved)}):")
        for run in preserved:
            typer.echo(
                f"  {run.manifest.run_uuid[:12]}... "
                f"tags={','.join(run.manifest.tags) or '—'}  "
                f"({run.manifest.description or '—'})"
            )
    return sized, total_bytes


def _execute_prune(
    sized: list[tuple[DiscoveredRun, int]],
    total_bytes: int,
) -> list[str]:
    """Hard-delete the selected run dirs; return the deleted run_uuids."""
    import shutil

    typer.echo("\nDeleting...")
    deleted_uuids: list[str] = []
    for run, _size in sized:
        shutil.rmtree(run.path)
        deleted_uuids.append(run.manifest.run_uuid)
        typer.echo(f"  removed {run.path}")
    typer.echo(f"Pruned {len(deleted_uuids)} run(s); freed {_human_bytes(total_bytes)}.")
    return deleted_uuids


def _maybe_invoke_resets(
    deleted_uuids: list[str],
    *,
    reset_exporter: bool,
    reset_prometheus: bool,
    reset_fuseki: bool,
    relaunch_exporter: bool = True,
) -> None:
    """Invoke the Phase G / H reset helpers based on the flag set."""
    from bffi_pipeline.runs_reset import (
        reset_exporter as _reset_exporter,
    )
    from bffi_pipeline.runs_reset import (
        reset_fuseki as _reset_fuseki,
    )
    from bffi_pipeline.runs_reset import (
        reset_prometheus as _reset_prometheus,
    )

    if reset_exporter:
        _reset_exporter(relaunch=relaunch_exporter)
    if reset_prometheus:
        _reset_prometheus(deleted_uuids)
    if reset_fuseki:
        _reset_fuseki()


def _filter_runs_for_listing(
    runs: list[DiscoveredRun],
    *,
    older_than: timedelta | None,
    statuses: list[str] | None,
    tags: list[str] | None,
) -> list[DiscoveredRun]:
    """Apply ``older-than`` / ``status`` / ``tag`` filters in AND semantics.

    Mirrors the ``select_for_pruning`` predicate but without the
    preservation rules (``keep_last`` / ``keep_tagged``) — listing just
    wants the included set.
    """
    if older_than is None and not statuses and not tags:
        return list(runs)
    current = datetime.now(UTC)
    out: list[DiscoveredRun] = []
    for run in runs:
        if older_than is not None:
            started = run.manifest.started_at
            if started.tzinfo is None:
                started = started.replace(tzinfo=UTC)
            if current - started < older_than:
                continue
        if statuses and run.manifest.status not in statuses:
            continue
        if tags:
            run_tags = set(run.manifest.tags)
            if not all(t in run_tags for t in tags):
                continue
        out.append(run)
    return out


def _sort_runs_for_listing(
    sized: list[tuple[DiscoveredRun, int]],
    *,
    sort_key: str,
) -> list[tuple[DiscoveredRun, int]]:
    """Sort ``(run, size)`` tuples for ``runs list``.

    ``started`` and ``ended`` are descending (newest first — operator
    expects "what's most recent"). ``size`` is descending (biggest
    first — operator expects "what's eating disk"). ``run_uuid`` is
    ascending (alphabetical — stable for diffing JSON output).
    """
    if sort_key == "started":
        return sorted(sized, key=lambda row: row[0].manifest.started_at, reverse=True)
    if sort_key == "ended":
        return sorted(
            sized,
            key=lambda row: row[0].manifest.ended_at or row[0].manifest.started_at,
            reverse=True,
        )
    if sort_key == "size":
        return sorted(sized, key=lambda row: row[1], reverse=True)
    # "run_uuid"
    return sorted(sized, key=lambda row: row[0].manifest.run_uuid)


def _render_runs_list_table(
    rows: list[tuple[DiscoveredRun, int]],
    *,
    total_matching: int,
    verbose: bool,
    runs_root: Path,
) -> None:
    """Render a fixed-column table to stdout."""
    if not rows:
        typer.echo(f"No runs match the filters under {runs_root}.")
        return

    header = f"{'RUN_UUID':<14}{'STARTED':<22}{'STATUS':<12}{'SIZE':>10}  TAGS / DESCRIPTION"
    typer.echo(header)
    typer.echo("-" * len(header))
    for run, size in rows:
        run_id = run.manifest.run_uuid[:12]
        started = (
            run.manifest.started_at.isoformat()
            if verbose
            else _relative_time(run.manifest.started_at)
        )
        tags = ",".join(run.manifest.tags) if run.manifest.tags else "—"
        desc = run.manifest.description or ""
        trailing = f"{tags}  {desc}".rstrip()
        typer.echo(
            f"{run_id:<14}"
            f"{started:<22}"
            f"{run.manifest.status:<12}"
            f"{_human_bytes(size):>10}  "
            f"{trailing}"
        )
    if len(rows) < total_matching:
        typer.echo(f"\n(Showing {len(rows)} of {total_matching} matching; pass --limit to widen.)")


def _render_runs_list_json(rows: list[tuple[DiscoveredRun, int]]) -> None:
    """Render ``rows`` as a JSON array of run objects to stdout."""
    import json as _json

    payload = [_run_to_listing_dict(run, size) for run, size in rows]
    typer.echo(_json.dumps(payload, indent=2, ensure_ascii=False))


def _render_runs_list_tsv(rows: list[tuple[DiscoveredRun, int]]) -> None:
    """Render ``rows`` as TSV (header + one row per run) to stdout."""
    columns = (
        "run_uuid",
        "started_at",
        "ended_at",
        "status",
        "size_bytes",
        "tags",
        "description",
    )
    typer.echo("\t".join(columns))
    for run, size in rows:
        ended = run.manifest.ended_at.isoformat() if run.manifest.ended_at else ""
        tags = ",".join(run.manifest.tags)
        desc = (run.manifest.description or "").replace("\t", " ").replace("\n", " ")
        typer.echo(
            "\t".join(
                (
                    run.manifest.run_uuid,
                    run.manifest.started_at.isoformat(),
                    ended,
                    run.manifest.status,
                    str(size),
                    tags,
                    desc,
                )
            )
        )


def _run_to_listing_dict(run: DiscoveredRun, size: int) -> dict[str, object]:
    """Project a :class:`DiscoveredRun` + size into the JSON listing schema."""
    return {
        "run_uuid": run.manifest.run_uuid,
        "started_at": run.manifest.started_at.isoformat(),
        "ended_at": (run.manifest.ended_at.isoformat() if run.manifest.ended_at else None),
        "status": run.manifest.status,
        "size_bytes": size,
        "tags": list(run.manifest.tags),
        "description": run.manifest.description,
        "path": str(run.path),
    }


_RELATIVE_TIME_WEEK_SECONDS = 7 * 24 * 60 * 60
_RELATIVE_TIME_DAY_SECONDS = 24 * 60 * 60
_RELATIVE_TIME_HOUR_SECONDS = 60 * 60
_RELATIVE_TIME_MINUTE_SECONDS = 60


def _relative_time(when: datetime) -> str:
    """Render a datetime as a short relative-time hint (e.g. ``3d ago``)."""
    now = datetime.now(UTC)
    anchor = when if when.tzinfo is not None else when.replace(tzinfo=UTC)
    delta = now - anchor
    secs = max(int(delta.total_seconds()), 0)
    if secs >= _RELATIVE_TIME_WEEK_SECONDS:
        return f"{secs // _RELATIVE_TIME_WEEK_SECONDS}w ago"
    if secs >= _RELATIVE_TIME_DAY_SECONDS:
        return f"{secs // _RELATIVE_TIME_DAY_SECONDS}d ago"
    if secs >= _RELATIVE_TIME_HOUR_SECONDS:
        return f"{secs // _RELATIVE_TIME_HOUR_SECONDS}h ago"
    if secs >= _RELATIVE_TIME_MINUTE_SECONDS:
        return f"{secs // _RELATIVE_TIME_MINUTE_SECONDS}m ago"
    return "just now"


_BYTES_PER_KB = 1024
_BYTES_PER_MB = 1024 * 1024
_BYTES_PER_GB = 1024 * 1024 * 1024


def _human_bytes(n: int) -> str:
    """Render a byte count as KB / MB / GB for operator-facing output."""
    if n < _BYTES_PER_KB:
        return f"{n} B"
    if n < _BYTES_PER_MB:
        return f"{n / _BYTES_PER_KB:.1f} KB"
    if n < _BYTES_PER_GB:
        return f"{n / _BYTES_PER_MB:.1f} MB"
    return f"{n / _BYTES_PER_GB:.2f} GB"


@app.callback()
def _root() -> None:
    """Root callback so subcommands attach cleanly.

    Runs the stale-provenance warning per spec § 8 every invocation;
    suppressed silently when no provenance file exists (first-run
    case, before any stage has emitted provenance). Also bootstraps the
    P-11 Phase A active observability emitter so every subcommand can
    emit events without per-command plumbing — read-only commands
    (``status``, ``workkey-stats``, etc.) simply never call
    ``emit_if_active`` and the registered emitter stays idle.
    """
    warning = prov_writer.stale_provenance_warning()
    if warning is not None:
        typer.echo(warning, err=True)
    _init_observability(get_settings())


@app.command("marc-to-bf")
def marc_to_bf_command(
    input_dir: Annotated[
        Path,
        typer.Argument(
            exists=True,
            file_okay=False,
            dir_okay=True,
            readable=True,
            resolve_path=True,
            help="Directory of MARCXML files (one record per file, named <bib_id>.xml).",
        ),
    ],
    output_dir: Annotated[
        Path | None,
        typer.Option(
            "--output-dir",
            "-o",
            help="Output directory; defaults to BFFI_DATA_DIR.",
            file_okay=False,
            dir_okay=True,
            resolve_path=True,
        ),
    ] = None,
    force: Annotated[
        bool,
        typer.Option(
            "--force",
            help="Reconvert records whose output is already newer than the input.",
        ),
    ] = False,
) -> None:
    """Convert MARCXML to BIBFRAME RDF/XML (M2)."""
    target = output_dir or get_settings().data_dir
    summary = marc_to_bf.run(input_dir, output_dir=target, force=force)
    typer.echo(summary.render())
    # Partial-failure exit policy: non-zero only when *nothing* made
    # progress (no successes, no idempotent skips). 800 k-record
    # batches always have a long tail of records missing 336/337/338
    # or 1XX/7XX — those are tracked in ``_errors.jsonl`` and visible
    # in summary.render(), but they must not abort a multi-stage shell
    # driver via ``set -e``.
    if summary.failed and not summary.succeeded and not summary.skipped_idempotent:
        raise typer.Exit(code=1)


@app.command("bf-to-bffi")
def bf_to_bffi_command(
    bibframe_dir: Annotated[
        Path | None,
        typer.Option(
            "--bibframe-dir",
            "-i",
            help="Directory of BIBFRAME RDF/XML files; defaults to <BFFI_DATA_DIR>/bibframe.",
            exists=True,
            file_okay=False,
            dir_okay=True,
            readable=True,
            resolve_path=True,
        ),
    ] = None,
    output_dir: Annotated[
        Path | None,
        typer.Option(
            "--output-dir",
            "-o",
            help="Output base; defaults to BFFI_DATA_DIR. BFFI Turtle goes to <output_dir>/bffi.",
            file_okay=False,
            dir_okay=True,
            resolve_path=True,
        ),
    ] = None,
    force: Annotated[
        bool,
        typer.Option(
            "--force",
            help="Reconvert records whose output is already newer than the input.",
        ),
    ] = False,
    llm_title_cascade: Annotated[
        bool,
        typer.Option(
            "--llm-title-cascade/--no-llm-title-cascade",
            help=(
                "Escalate ambiguous parallel-title records (e.g. 'X = Y = Z' with "
                "all-Latin segments Lingua maps to the same language) to the local "
                "Qwen3 cascade for per-segment language assignment. On by default; "
                "pass --no-llm-title-cascade to skip the LLM and stay graph-only."
            ),
        ),
    ] = True,
    llm_contrib_cascade: Annotated[
        bool,
        typer.Option(
            "--llm-contrib-cascade/--no-llm-contrib-cascade",
            help=(
                "Run the MARC 245$c contributor-extraction cascade on records "
                "whose 245$c contains capitalised name-tokens not covered by "
                "100/700. Off by default — fire rate is ~13% on the corpus "
                "and the M12 gold-set validation hasn't run yet."
            ),
        ),
    ] = False,
    primary_model: Annotated[
        str | None,
        typer.Option(
            "--primary-model",
            help="Override LLM_MODEL_PRIMARY for the title-language cascade.",
        ),
    ] = None,
) -> None:
    """Convert BIBFRAME RDF/XML to BFFI Turtle (M3).

    Boundary 3 SHACL failures are flagged in `_validation.jsonl` but do not
    cause a non-zero exit; only hard errors do.
    """
    target = output_dir or get_settings().data_dir
    detector: object | None = None
    if llm_title_cascade:
        from bffi_pipeline.title_lang_llm import LangChainTitleLangDetector

        detector = LangChainTitleLangDetector(model_name=primary_model)
    contrib_extractor: object | None = None
    if llm_contrib_cascade:
        from bffi_pipeline.contrib_extract_llm import LangChainContribExtractor

        contrib_extractor = LangChainContribExtractor(model_name=primary_model)
    summary = bf_to_bffi.run(
        bibframe_dir,
        output_dir=target,
        force=force,
        llm_detector=detector,
        contrib_extractor=contrib_extractor,
    )
    typer.echo(summary.render())
    # Partial-failure exit policy: see ``marc-to-bf`` for the
    # rationale. Errored records are listed in summary.render() and
    # do not abort the pipeline unless *every* record errored.
    if summary.errored and not summary.converted and not summary.skipped_idempotent:
        raise typer.Exit(code=1)


@app.command("status")
def status_command(
    sidecar: Annotated[
        Path | None,
        typer.Option(
            "--sidecar",
            help=(
                "Path to the stage-events.jsonl sidecar. Defaults to "
                "BFFI_OBSERVABILITY_SIDECAR (typically "
                "<BFFI_DATA_DIR>/stage-events.jsonl)."
            ),
            resolve_path=True,
        ),
    ] = None,
    tail: Annotated[
        bool,
        typer.Option(
            "--tail",
            help="Re-render the summary as new events arrive (polling, 200ms).",
        ),
    ] = False,
    since: Annotated[
        str | None,
        typer.Option(
            "--since",
            help=(
                "Filter to events with ts >= this ISO-8601 timestamp. "
                "Pass 'now' to anchor on the latest start event."
            ),
        ),
    ] = None,
    run_uuid: Annotated[
        str | None,
        typer.Option(
            "--run-uuid",
            help="Filter to a specific run_uuid (default: all runs in the file).",
        ),
    ] = None,
) -> None:
    """Render the current pipeline state from the P-11 stage-events sidecar.

    The events come from Phase A's per-stage emitters; this command is
    a pure consumer — it doesn't write any sidecar entries of its own,
    and the observability bootstrap in ``_root`` parks an emitter that
    stays idle here.
    """
    settings = get_settings()
    if sidecar is None:
        sidecar_str = settings.observability_sidecar.strip()
        if not sidecar_str:
            sidecar = settings.data_dir / "stage-events.jsonl"
        elif sidecar_str.lower() in {"none", "/dev/null", "off"}:
            typer.echo(
                "BFFI_OBSERVABILITY_SIDECAR disables the sidecar — nothing to read.",
                err=True,
            )
            raise typer.Exit(code=2)
        else:
            sidecar = Path(sidecar_str)

    since_dt = None
    if since is not None:
        if since.lower() == "now":
            # Anchor: latest `start` ts in the file. The CLI uses
            # ``now`` as shorthand for "the run that's actually running
            # right now", which in practice is the most recent start.
            rows = status_module.parse_sidecar(sidecar)
            start_rows = [r for r in rows if r.event == "start"]
            if start_rows:
                since_dt = start_rows[-1].ts
        else:
            try:
                from datetime import datetime as _dt

                since_dt = _dt.fromisoformat(since.replace("Z", "+00:00"))
            except ValueError as exc:
                typer.echo(f"Invalid --since timestamp: {since!r} ({exc})", err=True)
                raise typer.Exit(code=2) from exc

    if not tail:
        rows = status_module.parse_sidecar(sidecar, since=since_dt, run_uuid=run_uuid)
        typer.echo(status_module.render(status_module.collate(rows)))
        return

    # --tail: re-render on new events. Clean exit on Ctrl-C.
    try:
        for rendered in status_module.tail(sidecar, since=since_dt, run_uuid=run_uuid):
            typer.echo("\033[2J\033[H" + rendered)  # clear screen, home cursor
    except KeyboardInterrupt:
        typer.echo("", err=True)  # clean newline on exit


@app.command("serve-metrics")
def serve_metrics_command(
    port: Annotated[
        int,
        typer.Option(
            "--port",
            help="HTTP port to expose /metrics on. Default 9100.",
        ),
    ] = 9100,
    sidecar: Annotated[
        list[Path] | None,
        typer.Option(
            "--sidecar",
            help=(
                "Path to a stage-events.jsonl sidecar to tail. "
                "Repeatable — pass --sidecar multiple times to tail "
                "multiple sidecars from one exporter (P-17). Defaults "
                "to BFFI_OBSERVABILITY_SIDECAR / <BFFI_DATA_DIR>/stage-events.jsonl "
                "when neither --sidecar nor --watch-glob is given."
            ),
            resolve_path=True,
        ),
    ] = None,
    watch_glob: Annotated[
        list[str] | None,
        typer.Option(
            "--watch-glob",
            help=(
                "Glob pattern to auto-discover sidecars (P-17). "
                "Repeatable. Rescanned every --glob-rescan-seconds so "
                "fresh bench runs surface without restarting the "
                "exporter. Example: --watch-glob 'scratchpad/**/stage-events.jsonl'."
            ),
        ),
    ] = None,
    glob_rescan_seconds: Annotated[
        float,
        typer.Option(
            "--glob-rescan-seconds",
            help="Interval between --watch-glob rescans. Default 30.0.",
        ),
    ] = 30.0,
    poll_seconds: Annotated[
        float,
        typer.Option(
            "--poll-seconds",
            help="Tail-loop poll interval in seconds. Default 1.0.",
        ),
    ] = 1.0,
) -> None:
    """Run the P-11 Phase D Prometheus exporter.

    Tails one or more stage-events sidecars and exposes the canonical
    pipeline metric vocabulary at ``/metrics`` on the configured port.
    Designed to run for an arbitrarily long time independent of the
    pipeline — survives stage transitions and pipeline restarts.

    P-17: ``--sidecar`` is repeatable, ``--watch-glob`` auto-discovers
    sidecars, and each sidecar's co-located error JSONLs
    (``bibframe/_errors.jsonl``, ``bffi/_validation.jsonl``) are
    derived from the sidecar's PARENT DIR rather than a single global
    ``BFFI_DATA_DIR``. The startup log echoes the resolved set so the
    operator can confirm at a glance which sidecars + error files are
    being watched.

    Pair with the local Prometheus + Grafana stack via
    ``make observability-up`` (configured under ``docker-compose.yml``;
    Grafana auto-loads the provisioned bffi-pipeline dashboard).
    """
    settings = get_settings()
    sidecar_paths: list[Path] = list(sidecar or [])
    watch_globs: list[str] = list(watch_glob or [])

    # Resolve the default sidecar only when neither --sidecar nor
    # --watch-glob was given — operator who passes --watch-glob alone
    # expects discovery, not the implicit default attached too.
    if not sidecar_paths and not watch_globs:
        sidecar_str = settings.observability_sidecar.strip()
        if not sidecar_str:
            sidecar_paths.append(settings.data_dir / "stage-events.jsonl")
        elif sidecar_str.lower() in {"none", "/dev/null", "off"}:
            typer.echo(
                "BFFI_OBSERVABILITY_SIDECAR disables the sidecar — nothing to export.",
                err=True,
            )
            raise typer.Exit(code=2)
        else:
            sidecar_paths.append(Path(sidecar_str))

    # P-17: startup-log echoes the resolved set so the operator sees
    # at a glance which sidecars + co-located error files are being
    # watched — the gotcha from 2026-05-13 (silent stale-sidecar
    # tail) becomes immediately diagnosable.
    typer.echo(
        f"Serving Prometheus metrics at http://0.0.0.0:{port}/metrics",
        err=True,
    )
    if sidecar_paths:
        typer.echo(f"[bffi-pipeline] tailing sidecars ({len(sidecar_paths)}):", err=True)
        for sp in sidecar_paths:
            typer.echo(f"  {sp}", err=True)
            typer.echo(f"    + {sp.parent / 'bibframe' / '_errors.jsonl'}", err=True)
            typer.echo(f"    + {sp.parent / 'bffi' / '_validation.jsonl'}", err=True)
    if watch_globs:
        typer.echo(
            f"[bffi-pipeline] watch-globs ({len(watch_globs)}, rescan every "
            f"{glob_rescan_seconds:g}s):",
            err=True,
        )
        for g in watch_globs:
            typer.echo(f"  {g!r}", err=True)

    # P-32 Phase G: record this exporter's PID + launch argv so
    # `bffi-pipeline runs prune --apply --reset-exporter` can SIGTERM
    # + relaunch us with the same args. The pid file lives at
    # <BFFI_RUNS_ROOT>/.exporter.pid; cleaned up on graceful exit
    # via the exporter's atexit hook.
    import sys as _sys

    from bffi_pipeline.metrics_exporter import serve
    from bffi_pipeline.runs_reset import exporter_pid_file

    pid_path = exporter_pid_file(settings.runs_root)
    argv = [
        _sys.executable,
        "-m",
        "bffi_pipeline",
        "serve-metrics",
        *_reconstruct_serve_argv(
            port=port,
            sidecar_paths=sidecar_paths,
            watch_globs=watch_globs,
            glob_rescan_seconds=glob_rescan_seconds,
            poll_seconds=poll_seconds,
        ),
    ]

    try:
        serve(
            sidecar_paths,
            port=port,
            poll_seconds=poll_seconds,
            watch_globs=watch_globs or None,
            glob_rescan_seconds=glob_rescan_seconds,
            pid_file=pid_path,
            argv=argv,
        )
    except KeyboardInterrupt:
        typer.echo("\nExporter stopped.", err=True)


def _reconstruct_serve_argv(
    *,
    port: int,
    sidecar_paths: list[Path],
    watch_globs: list[str],
    glob_rescan_seconds: float,
    poll_seconds: float,
) -> list[str]:
    """Build the argv that ``--reset-exporter`` would relaunch with.

    Mirrors the operator's original ``bffi-pipeline serve-metrics``
    invocation as faithfully as we can reconstruct from the resolved
    options. Doesn't recover state that was supplied via env (e.g.
    BFFI_PROMETHEUS_URL) — the relaunched process inherits the
    parent's environment via ``subprocess.Popen`` default, so env
    vars survive.
    """
    args: list[str] = ["--port", str(port)]
    for sp in sidecar_paths:
        args += ["--sidecar", str(sp)]
    for g in watch_globs:
        args += ["--watch-glob", g]
    if glob_rescan_seconds != 30.0:  # noqa: PLR2004 — match the CLI default
        args += ["--glob-rescan-seconds", str(glob_rescan_seconds)]
    if poll_seconds != 1.0:
        args += ["--poll-seconds", str(poll_seconds)]
    return args


@app.command("plan")
def plan_command(
    stages: Annotated[
        list[str],
        typer.Argument(
            help=(
                "Stages this pipeline invocation will run, in order "
                "(e.g. m2 m3 m5 m6 m8 m9 skosify load). Emits one "
                "``plan`` stage-events row that the dashboard reads "
                "to distinguish ``pending`` (planned, not yet started) "
                "from ``skipped`` (not in plan)."
            ),
        ),
    ],
    description: Annotated[
        str,
        typer.Option(
            "--description",
            "-d",
            help=(
                "Free-text description of the run (e.g. 'Phase E A/B "
                "shot 1: submission ordering'). Surfaced in the "
                "dashboard's top header tile via the "
                "``bffi_run_description`` gauge."
            ),
        ),
    ] = "",
) -> None:
    """Declare the planned stage set + optional description for the active run.

    Runner scripts call this once at start with the full list of
    stages they intend to fire, so the dashboard's state tiles can
    render a real four-state model (pending / running / done /
    skipped). For ``BFFI_RUN_UUID`` continuity across subsequent
    subcommand invocations, the runner script should pin
    ``BFFI_RUN_UUID`` before invoking ``bffi-pipeline plan``.

    Direct subcommand invocations (e.g. ``bffi-pipeline reconcile``)
    do not need to call this — they'll show their single stage as
    ``running`` and every other stage as ``skipped``, which is the
    correct interpretation for a one-shot invocation.
    """
    from bffi_pipeline.stages.observability import emit_plan as _emit_plan

    _emit_plan(stages, description=description)
    rendered = ", ".join(stages)
    if description:
        typer.echo(f"Declared plan ({description}): {rendered}", err=True)
    else:
        typer.echo(f"Declared plan: {rendered}", err=True)


@app.command("workkey-stats")
def workkey_stats_command(
    path: Annotated[
        Path,
        typer.Argument(
            exists=True,
            readable=True,
            resolve_path=True,
            help=(
                "Path to a single BFFI Turtle file or to a data directory "
                "(with bffi/ and bibframe/ subdirs)."
            ),
        ),
    ],
) -> None:
    """Report Stage-1 block-size distribution (M4)."""
    graph = workkey.load_corpus(path)
    stats = workkey.compute_blocks(graph)
    typer.echo(stats.render())


@app.command("embed")
def embed_command(
    corpus_dir: Annotated[
        Path | None,
        typer.Option(
            "--corpus-dir",
            "-i",
            help="Data directory with bffi/ and bibframe/ subdirs; defaults to BFFI_DATA_DIR.",
            file_okay=False,
            dir_okay=True,
            readable=True,
            resolve_path=True,
        ),
    ] = None,
    output_dir: Annotated[
        Path | None,
        typer.Option(
            "--output-dir",
            "-o",
            help=(
                "Directory for embeddings.faiss and embeddings.idmap.json; "
                "defaults to BFFI_DATA_DIR."
            ),
            file_okay=False,
            dir_okay=True,
            resolve_path=True,
        ),
    ] = None,
    model_name: Annotated[
        str,
        typer.Option(
            "--model",
            help="HuggingFace model name (default BAAI/bge-m3).",
        ),
    ] = embeddings.DEFAULT_MODEL,
    device: Annotated[
        str,
        typer.Option(
            "--device",
            help="PyTorch device: mps (Apple Silicon), cuda, or cpu.",
        ),
    ] = embeddings.DEFAULT_DEVICE,
    batch_size: Annotated[
        int,
        typer.Option(
            "--batch-size",
            help="Embedding batch size (M5 Max saturates at 64-128).",
        ),
    ] = embeddings.DEFAULT_BATCH_SIZE,
    top_k: Annotated[
        int,
        typer.Option(
            "--top-k",
            help="Top-k neighbours per Work for candidate-pair generation.",
        ),
    ] = embeddings.DEFAULT_TOP_K,
    cross_block: Annotated[
        bool,
        typer.Option(
            "--cross-block",
            help="Keep candidate pairs whose Stage-1 blocking keys differ.",
        ),
    ] = False,
    force: Annotated[
        bool,
        typer.Option(
            "--force",
            help="Rebuild the index even when persisted files are newer than inputs.",
        ),
    ] = False,
) -> None:
    """Build the FAISS HNSW index and emit candidate pairs (M5)."""
    target = output_dir or get_settings().data_dir
    build_result = embeddings.build_index(
        corpus_dir,
        output_dir=target,
        model_name=model_name,
        device=device,
        batch_size=batch_size,
        force=force,
    )
    typer.echo(build_result.render())
    stats = embeddings.query_candidates(target, top_k=top_k, cross_block=cross_block)
    typer.echo(stats.render())


@app.command("embed-benchmark")
def embed_benchmark_command(
    models: Annotated[
        list[str] | None,
        typer.Option(
            "--model",
            help=(
                "HuggingFace model name; pass multiple times to compare. "
                "Defaults to BGE-M3 / multilingual-e5-large / jina-v3."
            ),
        ),
    ] = None,
    gold_path: Annotated[
        Path | None,
        typer.Option(
            "--gold-path",
            help="Path to gold/gold.jsonl; defaults to repo gold/ directory.",
            exists=True,
            file_okay=True,
            dir_okay=False,
            readable=True,
            resolve_path=True,
        ),
    ] = None,
    device: Annotated[
        str,
        typer.Option(
            "--device",
            help="PyTorch device: mps (Apple Silicon), cuda, or cpu.",
        ),
    ] = embeddings.DEFAULT_DEVICE,
    batch_size: Annotated[
        int,
        typer.Option(
            "--batch-size",
            help="Embedding batch size.",
        ),
    ] = embeddings.DEFAULT_BATCH_SIZE,
) -> None:
    """Compare embedding models on the gold set's same_work / different_work gap (M5 / M12)."""
    candidate_models = tuple(models) if models else embed_benchmark.DEFAULT_MODELS
    results = embed_benchmark.benchmark_models(
        models=candidate_models,
        gold_path=gold_path,
        device=device,
        batch_size=batch_size,
    )
    typer.echo(embed_benchmark.render_comparison(results))


@app.command("eval")
def eval_command(
    run_label: Annotated[
        str,
        typer.Option(
            "--run-label",
            help=(
                "Identifier for this run (e.g. 'qwen3-32b-prompt-v3'). Becomes the "
                "filename stem under --output-dir and is recorded in the JSON summary."
            ),
        ),
    ],
    gold_path: Annotated[
        Path | None,
        typer.Option(
            "--gold-path",
            help="Path to gold/gold.jsonl; defaults to repo gold/ directory.",
            exists=True,
            file_okay=True,
            dir_okay=False,
            readable=True,
            resolve_path=True,
        ),
    ] = None,
    output_dir: Annotated[
        Path | None,
        typer.Option(
            "--output-dir",
            help=("Directory for the JSON summary; defaults to <repo>/eval-runs (gitignored)."),
            file_okay=False,
            dir_okay=True,
            resolve_path=True,
        ),
    ] = None,
) -> None:
    """Score the gold set against the M6 judge and write a JSON summary (M12).

    Eval is **not in CI** per spec § 9; this subcommand is invoked
    locally on the M5 Max via ``make eval`` before any PR that touches
    prompts / gold / judge code. The text rendering is paste-ready for
    the PR description; the JSON file is the durable record.
    """
    summary, out_path = eval_harness.run_eval(
        run_label=run_label,
        gold_path=gold_path,
        output_dir=output_dir,
    )
    typer.echo(eval_harness.render_text(summary))
    typer.echo("")
    typer.echo(f"Summary written to {out_path}")


@app.command("grow-gold")
def grow_gold_command(
    fuseki_url: Annotated[
        str | None,
        typer.Option(
            "--fuseki-url",
            help="Fuseki dataset base URL; defaults to FUSEKI_URL.",
        ),
    ] = None,
    output_path: Annotated[
        Path | None,
        typer.Option(
            "--output-path",
            help=(
                "Where to write the candidate JSONL; defaults to "
                "gold/grow-candidates.jsonl in the repo."
            ),
            file_okay=True,
            dir_okay=False,
            resolve_path=True,
        ),
    ] = None,
) -> None:
    """Grow the gold set from human-overridden judge decisions (M12 phase 3).

    Run monthly per spec § 9. Writes a JSONL of candidate cases the
    cataloguer reviews — each row needs ``category`` filled in by hand
    before being merged into ``gold/gold.jsonl``. New cases default to
    ``holdout: false``; cataloguers flip the flag explicitly when a
    case should join the eval set.
    """
    result = eval_grow.grow(
        fuseki_url=fuseki_url,
        output_path=output_path,
    )
    typer.echo(result.render())


@app.command("embed-stats")
def embed_stats_command(
    output_dir: Annotated[
        Path | None,
        typer.Option(
            "--output-dir",
            "-o",
            help="Directory holding embeddings.faiss + idmap; defaults to BFFI_DATA_DIR.",
            file_okay=False,
            dir_okay=True,
            readable=True,
            resolve_path=True,
        ),
    ] = None,
    top_k: Annotated[
        int,
        typer.Option("--top-k", help="Top-k neighbours per Work."),
    ] = embeddings.DEFAULT_TOP_K,
    cross_block: Annotated[
        bool,
        typer.Option(
            "--cross-block",
            help="Keep candidate pairs whose Stage-1 blocking keys differ.",
        ),
    ] = False,
) -> None:
    """Report band counts and similarity distribution from the persisted index (M5)."""
    target = output_dir or get_settings().data_dir
    stats = embeddings.query_candidates(target, top_k=top_k, cross_block=cross_block)
    typer.echo(stats.render())


@app.command("judge")
def judge_command(
    candidates_path: Annotated[
        Path | None,
        typer.Option(
            "--candidates-path",
            "-i",
            help="M5 embed-candidates.jsonl; defaults to <BFFI_DATA_DIR>/embed-candidates.jsonl.",
            exists=True,
            file_okay=True,
            dir_okay=False,
            readable=True,
            resolve_path=True,
        ),
    ] = None,
    output_path: Annotated[
        Path | None,
        typer.Option(
            "--output-path",
            "-o",
            help="Per-pair decisions JSONL; defaults to <BFFI_DATA_DIR>/judge-decisions.jsonl.",
            file_okay=True,
            dir_okay=False,
            resolve_path=True,
        ),
    ] = None,
    bffi_corpus_dir: Annotated[
        Path | None,
        typer.Option(
            "--bffi-corpus-dir",
            help=(
                "Directory holding bffi/*.ttl + bibframe/*.rdf so the judge can resolve "
                "Work URIs to WorkRecord; defaults to BFFI_DATA_DIR."
            ),
            exists=True,
            file_okay=False,
            dir_okay=True,
            resolve_path=True,
        ),
    ] = None,
    primary_model: Annotated[
        str | None,
        typer.Option(
            "--primary-model",
            help="Override LLM_MODEL_PRIMARY for this run.",
        ),
    ] = None,
    fallback_model: Annotated[
        str | None,
        typer.Option(
            "--fallback-model",
            help="Override LLM_MODEL_FALLBACK for this run.",
        ),
    ] = None,
    restart: Annotated[
        bool,
        typer.Option(
            "--restart",
            help="Wipe the output JSONL and checkpoint and re-run from scratch.",
        ),
    ] = False,
    provenance: Annotated[
        bool,
        typer.Option(
            "--provenance/--no-provenance",
            help=(
                "Emit per-decision bffi-prov:WorkMergeDecision Activities to "
                "<BFFI_DATA_DIR>/provenance.ttl (spec § 8). On by default; the "
                "off-switch is for local development."
            ),
        ),
    ] = True,
    provenance_path: Annotated[
        Path | None,
        typer.Option(
            "--provenance-path",
            help="Path to provenance.ttl; defaults to <BFFI_DATA_DIR>/provenance.ttl.",
            file_okay=True,
            dir_okay=False,
            resolve_path=True,
        ),
    ] = None,
    concurrency: Annotated[
        int,
        typer.Option(
            "--concurrency",
            help=(
                "Pairs to judge in parallel. Default 1 (Ollama serial); mlx-lm "
                "production runs sweep {4, 8, 16, 32} per spec § 11. Output JSONL "
                "stays in input order; the checkpoint advances contiguously."
            ),
            min=1,
        ),
    ] = judge.DEFAULT_CONCURRENCY,
    full_rationale: Annotated[
        bool,
        typer.Option(
            "--full-rationale/--no-full-rationale",
            help=(
                "Require a substantive natural-language rationale on every "
                "judge call (default on). Pass --no-full-rationale to switch "
                "to the fast prompt (judge_v1_fast.txt): the LLM may set "
                "rationale=null for 'same_work' / 'different_work' decisions "
                "with confidence ≥ 0.85. Rationale stays required for "
                "'uncertain' or lower-confidence outcomes (where it drives "
                "the human-review queue and the cascade re-run). At corpus "
                "scale fast mode cuts ~50-200 generation tokens per high-"
                "confidence pair; the audit trail keeps the structured "
                "matching_fields / diverging_fields / confidence evidence."
            ),
        ),
    ] = True,
    abort_budget_seconds: Annotated[
        int | None,
        typer.Option(
            "--abort-budget-seconds",
            help=(
                "Per-call LLM wall-time ceiling. Overrides "
                "LLM_CALL_TIMEOUT_SECONDS for this run. When a single "
                "LLM call exceeds this budget, the cascade's existing "
                "retry stack (5/30/120 s) retries the same pair on the "
                "same model first; only after retries exhaust on both "
                "primary and fallback does the pair land as "
                "'uncertain' with bffi-prov:stage='watchdog-aborted'. "
                "Watchdog events stream to stderr (prefix 'WATCHDOG_EVENT') "
                "and to <BFFI_DATA_DIR>/watchdog-events.jsonl for "
                "post-run audit. See docs/plans/completed/p-03-m6-stall-watchdog.md."
            ),
            min=1,
        ),
    ] = None,
    pair_budget_seconds: Annotated[
        int | None,
        typer.Option(
            "--pair-budget-seconds",
            help=(
                "Per-pair LLM wall-time ceiling for the whole cascade "
                "(primary + fallback + retries). Overrides "
                "LLM_PAIR_TIMEOUT_SECONDS for this run. Orthogonal to "
                "--abort-budget-seconds: catches pairs where many "
                "legitimate calls pile up to a long pair time even "
                "when no single call exceeds the per-call ceiling. "
                "Pairs exceeding this budget land as 'uncertain' with "
                "bffi-prov:stage='watchdog-aborted' and emit a "
                "'pair_budget_exceeded' watchdog event. See "
                "docs/plans/completed/p-03-m6-stall-watchdog.md Phase B."
            ),
            min=1,
        ),
    ] = None,
) -> None:
    """Run the cascade judge over M5's escalate-band candidate pairs (M6)."""
    settings = get_settings()
    if abort_budget_seconds is not None:
        # Mutate the cached Settings singleton in place. The judge stage
        # reads ``settings.llm_call_timeout_seconds`` lazily inside
        # ``_build_chain`` so this override propagates without further
        # plumbing.
        settings.llm_call_timeout_seconds = abort_budget_seconds
    if pair_budget_seconds is not None:
        settings.llm_pair_timeout_seconds = pair_budget_seconds
    target_output = output_path or (settings.data_dir / judge.DECISIONS_FILENAME)

    def _on_progress(snapshot: judge.JudgeBatchProgress) -> None:
        typer.echo(snapshot.render())

    if provenance:
        with prov_writer.ProvenanceWriter(provenance_path) as writer:
            result = judge.judge_batch(
                candidates_path,
                target_output,
                bffi_corpus_dir=bffi_corpus_dir,
                resume=not restart,
                primary_model=primary_model,
                fallback_model=fallback_model,
                progress_callback=_on_progress,
                provenance_writer=writer,
                concurrency=concurrency,
                full_rationale=full_rationale,
            )
    else:
        result = judge.judge_batch(
            candidates_path,
            target_output,
            bffi_corpus_dir=bffi_corpus_dir,
            resume=not restart,
            primary_model=primary_model,
            fallback_model=fallback_model,
            progress_callback=_on_progress,
            concurrency=concurrency,
            full_rationale=full_rationale,
        )
    typer.echo(result.render())


@app.command("merge")
def merge_command(
    decisions_path: Annotated[
        Path | None,
        typer.Option(
            "--decisions-path",
            help="M6 judge-decisions.jsonl; defaults to <BFFI_DATA_DIR>/judge-decisions.jsonl.",
            exists=True,
            file_okay=True,
            dir_okay=False,
            readable=True,
            resolve_path=True,
        ),
    ] = None,
    bffi_corpus_dir: Annotated[
        Path | None,
        typer.Option(
            "--bffi-corpus-dir",
            help="Directory holding bffi/*.ttl + bibframe/*.rdf; defaults to BFFI_DATA_DIR.",
            exists=True,
            file_okay=False,
            dir_okay=True,
            resolve_path=True,
        ),
    ] = None,
    output_path: Annotated[
        Path | None,
        typer.Option(
            "--output-path",
            "-o",
            help="canonical.ttl path; defaults to <BFFI_DATA_DIR>/canonical.ttl.",
            file_okay=True,
            dir_okay=False,
            resolve_path=True,
        ),
    ] = None,
    map_path: Annotated[
        Path | None,
        typer.Option(
            "--map-path",
            help="canonical-map.jsonl path; defaults to <BFFI_DATA_DIR>/canonical-map.jsonl.",
            file_okay=True,
            dir_okay=False,
            resolve_path=True,
        ),
    ] = None,
    helmet_map_path: Annotated[
        Path | None,
        typer.Option(
            "--helmet-map-path",
            help="M2 helmet-map.jsonl; defaults to <BFFI_DATA_DIR>/helmet-map.jsonl.",
            file_okay=True,
            dir_okay=False,
            readable=True,
            resolve_path=True,
        ),
    ] = None,
) -> None:
    """Apply judge decisions to mint canonical Works (M8)."""
    result = merge.apply_merge(
        decisions_path,
        bffi_corpus_dir,
        output_path=output_path,
        map_path=map_path,
        helmet_map_path=helmet_map_path,
    )
    typer.echo(result.render())


_RECONCILE_KIND_GROUPS: dict[str, frozenset[reconcile.AuthorityKind]] = {
    "creators": frozenset({"person", "corporate_body"}),
    "subjects": frozenset({"subject"}),
    "genres": frozenset({"genre_form", "music_form"}),
    "all": reconcile.ALL_AUTHORITY_KINDS,
}


def _parse_reconcile_kinds(raw: str | None) -> frozenset[reconcile.AuthorityKind] | None:
    """Parse the ``--kinds`` CLI option into a runtime kind set.

    ``None`` (or ``"all"``, or whitespace) returns ``None`` so the
    orchestrator runs every kind by default. Unknown groups raise
    ``typer.BadParameter`` so cataloguers see the typo immediately.
    """
    if raw is None or not raw.strip():
        return None
    selected: set[reconcile.AuthorityKind] = set()
    for token in raw.split(","):
        name = token.strip().casefold()
        if not name:
            continue
        if name == "all":
            return None
        group = _RECONCILE_KIND_GROUPS.get(name)
        if group is None:
            raise typer.BadParameter(
                f"Unknown --kinds group {name!r}; choose from {sorted(_RECONCILE_KIND_GROUPS)}."
            )
        selected.update(group)
    return frozenset(selected) if selected else None


@app.command("reconcile")
def reconcile_command(
    canonical_path: Annotated[
        Path | None,
        typer.Option(
            "--canonical-path",
            "-i",
            help="Path to canonical.ttl; defaults to <BFFI_DATA_DIR>/canonical.ttl.",
            exists=True,
            file_okay=True,
            dir_okay=False,
            readable=True,
            resolve_path=True,
        ),
    ] = None,
    output_path: Annotated[
        Path | None,
        typer.Option(
            "--output-path",
            "-o",
            help="Where to write the reconciled Turtle. Defaults to overwriting --canonical-path.",
            file_okay=True,
            dir_okay=False,
            resolve_path=True,
        ),
    ] = None,
    primary_model: Annotated[
        str | None,
        typer.Option(
            "--primary-model",
            help="Override LLM_MODEL_PRIMARY for this run.",
        ),
    ] = None,
    provenance: Annotated[
        bool,
        typer.Option(
            "--provenance/--no-provenance",
            help=(
                "Append per-attempt bffi-prov:Reconciliation Activities to "
                "<BFFI_DATA_DIR>/provenance.ttl. On by default."
            ),
        ),
    ] = True,
    provenance_path: Annotated[
        Path | None,
        typer.Option(
            "--provenance-path",
            help="Path to provenance.ttl; defaults to <BFFI_DATA_DIR>/provenance.ttl.",
            file_okay=True,
            dir_okay=False,
            resolve_path=True,
        ),
    ] = None,
    kinds: Annotated[
        str | None,
        typer.Option(
            "--kinds",
            help=(
                "Comma-separated reconciliation groups to run. Choices: "
                "'creators' (KANTO+VIAF persons/corporate bodies), "
                "'subjects' (YSO topical), 'genres' (KAUNO + MUSO music form), "
                "or 'all'. Default is all."
            ),
        ),
    ] = None,
    local_resolver: Annotated[
        bool,
        typer.Option(
            "--local-resolver/--no-local-resolver",
            help=(
                "Tier-0 lookup: try an exact prefLabel match against the local "
                "Fuseki authority graphs (YSO/KAUNO/MUSO/SLM) before calling "
                "Finto. Avoids ~one HTTP round-trip per cataloguer literal at "
                "corpus scale. On by default; pass --no-local-resolver to "
                "force every literal through the Finto API."
            ),
        ),
    ] = True,
    concurrency: Annotated[
        int,
        typer.Option(
            "--concurrency",
            help=(
                "ThreadPoolExecutor max_workers for the tier-2 picker dispatch. "
                "tier-0 / tier-1 / tier-3 stay single-threaded. Defaults to "
                "M9_CONCURRENCY from the env / .env (typically 4). Set 1 to "
                "restore pre-Phase-A sequential behaviour. See "
                "docs/plans/backlog/p-10-m9-reconcile-throughput.md Phase A."
            ),
        ),
    ] = -1,
    field_timeout: Annotated[
        int,
        typer.Option(
            "--field-timeout-seconds",
            help=(
                "Per-field wall budget for the picker (tier-2). On exceed, the "
                "field is marked bffi-prov:stage='watchdog-aborted' and falls "
                "through to tier-3 fallback. Defaults to "
                "LLM_M9_FIELD_TIMEOUT_SECONDS. Set 0 to disable the budget."
            ),
        ),
    ] = -1,
    phase1_concurrency: Annotated[
        int,
        typer.Option(
            "--phase1-concurrency",
            help=(
                "ThreadPoolExecutor max_workers for the Phase 1 pre-pass "
                "(tier-0 SPARQL + Finto/VIAF candidate query). Separate from "
                "--concurrency (tier-2 picker, GPU-bound) because Phase 1's "
                "binding constraint is HTTP/SPARQL throughput. Defaults to "
                "M9_PHASE1_CONCURRENCY (typically 8). Set 1 to restore the "
                "post-Phase-A serial pre-pass. See "
                "docs/plans/in-progress/p-10-m9-reconcile-throughput.md Phase A2."
            ),
        ),
    ] = -1,
    tier0_expansion: Annotated[
        bool | None,
        typer.Option(
            "--tier0-expansion/--no-tier0-expansion",
            help=(
                "P-10 Phase C: enable the folded-lookup tier-0 path "
                "(matches bffi:foldedLabel materialised by load-finto). "
                "Bindings that required the fold are flagged "
                "bffi:descriptionAuthentication=needs-review for cataloguer "
                "audit. Defaults to BFFI_M9_TIER0_EXPANSION from the env "
                "(off until the 200-sample audit confirms zero false "
                "positives on this corpus). See "
                "docs/plans/in-progress/p-10-m9-reconcile-throughput.md Phase C."
            ),
        ),
    ] = None,
    cache: Annotated[
        bool | None,
        typer.Option(
            "--cache/--no-cache",
            help=(
                "P-10 Phase B: enable the persistent picker decision cache "
                "(<data_dir>/reconcile-cache.sqlite). Cached verdicts skip "
                "the LLM picker entirely on the next run; per-vocabulary "
                "Finto-dump SHA-256 invalidates the cache on refresh. "
                "Defaults to ON unless BFFI_M9_CACHE_DISABLED=1. Pass "
                "--no-cache to bench a cold run without disabling the env "
                "var. See docs/plans/in-progress/p-10-m9-reconcile-"
                "throughput.md Phase B."
            ),
        ),
    ] = None,
) -> None:
    """Reconcile canonical Work creators + subjects against KANTO / VIAF / YSO / KAUNO / MUSO."""
    settings = get_settings()
    target = output_path or canonical_path or (settings.data_dir / "canonical.ttl")
    selected_kinds = _parse_reconcile_kinds(kinds)
    # ``-1`` sentinels mean "fall through to settings"; explicit 0 / 1 / 4 from
    # the CLI override the env. This keeps Phase A's rollback knob ergonomic
    # (`--concurrency 1 --field-timeout-seconds 0`) without forcing the
    # operator to also unset the env vars.
    effective_concurrency = settings.m9_concurrency if concurrency < 0 else concurrency
    effective_field_timeout = (
        settings.llm_m9_field_timeout_seconds if field_timeout < 0 else field_timeout
    )
    effective_phase1_concurrency = (
        settings.m9_phase1_concurrency if phase1_concurrency < 0 else phase1_concurrency
    )
    effective_tier0_expansion = (
        settings.m9_tier0_expansion if tier0_expansion is None else tier0_expansion
    )
    # P-10 Phase E: validated string → typed Literal for apply_reconciliation.
    # Env-var only (no CLI flag); see plan § E.2.
    if settings.m9_picker_ordering not in (
        reconcile.PICKER_ORDERING_PREFIX_CACHE,
        reconcile.PICKER_ORDERING_SUBMISSION,
    ):
        raise typer.BadParameter(
            f"BFFI_M9_PICKER_ORDERING must be "
            f"'{reconcile.PICKER_ORDERING_PREFIX_CACHE}' or "
            f"'{reconcile.PICKER_ORDERING_SUBMISSION}'; "
            f"got {settings.m9_picker_ordering!r}."
        )
    effective_picker_ordering: reconcile.PickerOrdering = (
        reconcile.PICKER_ORDERING_PREFIX_CACHE
        if settings.m9_picker_ordering == reconcile.PICKER_ORDERING_PREFIX_CACHE
        else reconcile.PICKER_ORDERING_SUBMISSION
    )
    # P-10 Phase B: cache resolution. The --no-cache flag wins over the env
    # var (operator-friendly bench knob); the env var BFFI_M9_CACHE_DISABLED
    # is the durable rollback. None means "fall through to env".
    cache_enabled = (not settings.m9_cache_disabled) if cache is None else cache
    watchdog_sidecar = settings.data_dir / "watchdog-events.jsonl"

    http_client = httpx.Client(timeout=10.0)
    picker_cache: reconcile.PickerCache | None = (
        reconcile.PickerCache(reconcile.picker_cache_default_path()) if cache_enabled else None
    )
    try:
        client = reconcile.FintoSkosmosClient(http_client=http_client)
        fallback = reconcile.ViafClient(http_client=http_client)

        # Picker factory: at c>=2 the orchestrator builds one
        # ``LangChainLLMPicker`` per worker thread (LangChain's
        # underlying OpenAI-compat client has no documented
        # thread-safety guarantee; one client per thread is cheap).
        # At c=1 the factory is called once.
        def picker_factory() -> reconcile.LLMPicker:
            return reconcile.LangChainLLMPicker(model_name=primary_model)

        resolver: local_concept_resolver.LocalConceptResolver | None = (
            local_concept_resolver.FusekiConceptResolver(
                http_client=http_client,
                fuseki_url=settings.fuseki_url,
                tier0_expansion_enabled=effective_tier0_expansion,
            )
            if local_resolver
            else None
        )

        if provenance:
            with prov_writer.ProvenanceWriter(provenance_path) as writer:
                summary, _outcomes = reconcile.apply_reconciliation(
                    canonical_path,
                    output_path=target,
                    client=client,
                    fallback_client=fallback,
                    picker_factory=picker_factory,
                    provenance_graph=writer.graph,
                    kinds=selected_kinds,
                    local_resolver=resolver,
                    concurrency=effective_concurrency,
                    field_timeout_seconds=effective_field_timeout,
                    watchdog_sidecar_path=watchdog_sidecar,
                    phase1_concurrency=effective_phase1_concurrency,
                    picker_ordering=effective_picker_ordering,
                    picker_cache=picker_cache,
                    lexical_fallback_floor=settings.m9_lexical_fallback_floor,
                    lexical_fallback_floor_per_vocab=settings.m9_lexical_fallback_floor_per_vocab,
                    disable_fallback=settings.m9_disable_fallback,
                )
        else:
            summary, _outcomes = reconcile.apply_reconciliation(
                canonical_path,
                output_path=target,
                client=client,
                fallback_client=fallback,
                picker_factory=picker_factory,
                kinds=selected_kinds,
                local_resolver=resolver,
                concurrency=effective_concurrency,
                field_timeout_seconds=effective_field_timeout,
                watchdog_sidecar_path=watchdog_sidecar,
                phase1_concurrency=effective_phase1_concurrency,
                picker_ordering=effective_picker_ordering,
                picker_cache=picker_cache,
                lexical_fallback_floor=settings.m9_lexical_fallback_floor,
                lexical_fallback_floor_per_vocab=settings.m9_lexical_fallback_floor_per_vocab,
                disable_fallback=settings.m9_disable_fallback,
            )
    finally:
        http_client.close()
        if picker_cache is not None:
            picker_cache.close()
    typer.echo(summary.render())


@app.command("ysa-disambiguation-report")
def ysa_disambiguation_report_command(
    canonical_path: Annotated[
        Path | None,
        typer.Option(
            "--canonical-path",
            "-i",
            help="Path to canonical.ttl; defaults to <BFFI_DATA_DIR>/canonical.ttl.",
            exists=True,
            file_okay=True,
            dir_okay=False,
            readable=True,
            resolve_path=True,
        ),
    ] = None,
    output_path: Annotated[
        Path | None,
        typer.Option(
            "--output-path",
            "-o",
            help=("CSV path; defaults to <BFFI_DATA_DIR>/ysa-disambiguation-report.csv."),
            file_okay=True,
            dir_okay=False,
            resolve_path=True,
        ),
    ] = None,
) -> None:
    """Emit a cataloguer-review CSV for YSA → YSO disambiguation residue.

    Walks canonical.ttl for subject literals that look like
    pre-2018 bare YSA forms (``lapset``, ``2000-luku``, …) and
    queries the locally-loaded YSO graph for the disambiguated forms
    YSO replaced them with. One row per (helmet_bib_id, literal,
    candidate) tuple; see ``docs/runbook.md`` for the operational
    background and the SPARQL needs-review filter this report
    complements.
    """
    summary = ysa_disambiguation_report.run(
        canonical_path=canonical_path,
        output_path=output_path,
    )
    typer.echo(summary.render())


@app.command("skosify")
def skosify_command(
    canonical_path: Annotated[
        Path | None,
        typer.Option(
            "--canonical-path",
            "-i",
            help="Path to canonical.ttl; defaults to <BFFI_DATA_DIR>/canonical.ttl.",
            exists=True,
            file_okay=True,
            dir_okay=False,
            readable=True,
            resolve_path=True,
        ),
    ] = None,
    output_path: Annotated[
        Path | None,
        typer.Option(
            "--output-path",
            "-o",
            help=(
                "Path to canonical-skosified.ttl; "
                "defaults to <BFFI_DATA_DIR>/canonical-skosified.ttl."
            ),
            file_okay=True,
            dir_okay=False,
            resolve_path=True,
        ),
    ] = None,
    overlay_path: Annotated[
        Path | None,
        typer.Option(
            "--overlay-path",
            help=(
                "Path to bffi-skos-overlay.ttl; defaults to "
                "config/overlay/bffi-skos-overlay.ttl in the repo."
            ),
            exists=True,
            file_okay=True,
            dir_okay=False,
            readable=True,
            resolve_path=True,
        ),
    ] = None,
    config_path: Annotated[
        Path | None,
        typer.Option(
            "--config-path",
            help="Path to bffi.cfg; defaults to config/bffi.cfg in the repo.",
            exists=True,
            file_okay=True,
            dir_okay=False,
            readable=True,
            resolve_path=True,
        ),
    ] = None,
    force: Annotated[
        bool,
        typer.Option(
            "--force",
            help="Re-run Skosify even when the existing output is newer than the inputs.",
        ),
    ] = False,
) -> None:
    """Run Skosify with the BFFI overlay to produce dual-typed output (M10 phase 1)."""
    result = skosify_run.run(
        canonical_path,
        output_path=output_path,
        overlay_path=overlay_path,
        config_path=config_path,
        force=force,
    )
    typer.echo(result.render())


@app.command("load")
def load_command(
    skosified_path: Annotated[
        Path | None,
        typer.Option(
            "--skosified-path",
            help=(
                "Path to canonical-skosified.ttl from M10 phase 1; "
                "defaults to <BFFI_DATA_DIR>/canonical-skosified.ttl."
            ),
            file_okay=True,
            dir_okay=False,
            readable=True,
            resolve_path=True,
        ),
    ] = None,
    admin_vocab_path: Annotated[
        Path | None,
        typer.Option(
            "--admin-vocab-path",
            help=(
                "Path to bffi-admin-vocabulary.ttl; "
                "defaults to config/bffi-admin-vocabulary.ttl in the repo."
            ),
            file_okay=True,
            dir_okay=False,
            readable=True,
            resolve_path=True,
        ),
    ] = None,
    provenance_path: Annotated[
        Path | None,
        typer.Option(
            "--provenance-path",
            help="Path to provenance.ttl; defaults to <BFFI_DATA_DIR>/provenance.ttl.",
            file_okay=True,
            dir_okay=False,
            readable=True,
            resolve_path=True,
        ),
    ] = None,
    fuseki_url: Annotated[
        str | None,
        typer.Option(
            "--fuseki-url",
            help="Fuseki dataset endpoint; defaults to FUSEKI_URL from settings.",
        ),
    ] = None,
    no_clear_fuseki: Annotated[
        bool,
        typer.Option(
            "--no-clear-fuseki",
            help=(
                "Skip the P-32 Phase H pre-run Fuseki clear. By default the "
                "loader drops every named graph under settings.graph_base "
                "before loading so the resulting Fuseki state is a pure "
                "function of this run's canonical-skosified.ttl. Pass this "
                "flag to layer on top of existing state (debugging / "
                "side-by-side comparison)."
            ),
        ),
    ] = False,
    force_clear: Annotated[
        bool,
        typer.Option(
            "--force-clear",
            help=(
                "Bypass the BFFI_FUSEKI_CLEAR_MAX_TRIPLES safety threshold. "
                "Only needed when the operator has accidentally pointed "
                "settings.graph_base at a vocabulary URI prefix and wants "
                "to drop those big graphs anyway."
            ),
        ),
    ] = False,
) -> None:
    """Load skosified data + provenance into Fuseki and run Boundary-5 smokes (M10)."""
    settings = get_settings()
    auth: tuple[str, str] | None = (
        (settings.fuseki_user, settings.fuseki_password)
        if settings.fuseki_user and settings.fuseki_password
        else None
    )
    with httpx.Client(timeout=30.0, auth=auth) as client:
        # P-32 Phase H: pre-run Fuseki clear. Best-effort default; the
        # operator's --no-clear-fuseki opts out per-invocation,
        # BFFI_FUSEKI_CLEAR_ON_RUN_START=false / strict tunes the
        # setting globally.
        _maybe_clear_fuseki_before_load(
            fuseki_url=fuseki_url or settings.fuseki_url,
            graph_base=settings.graph_base,
            no_clear_flag=no_clear_fuseki,
            force_clear_flag=force_clear,
            client=client,
        )

        result = load.run(
            skosified_path=skosified_path,
            admin_vocab_path=admin_vocab_path,
            provenance_path=provenance_path,
            fuseki_url=fuseki_url,
            client=client,
        )
    typer.echo(result.render())


def _maybe_clear_fuseki_before_load(
    *,
    fuseki_url: str,
    graph_base: str,
    no_clear_flag: bool,
    force_clear_flag: bool,
    client: httpx.Client,
) -> None:
    """P-32 Phase H: clear Fuseki at the start of ``bffi-pipeline load``.

    Gated by ``BFFI_FUSEKI_CLEAR_ON_RUN_START`` (``true`` default;
    ``false`` skips; ``strict`` makes unreachable Fuseki fatal) AND
    the CLI's ``--no-clear-fuseki`` opt-out. Records the outcome on
    the run manifest's ``pre_run_fuseki_clear`` field.
    """
    from bffi_pipeline.run_manifest import MANIFEST_FILENAME, update_manifest_field
    from bffi_pipeline.stages.fuseki_clear import clear_run_output_graphs

    settings = get_settings()
    mode = settings.fuseki_clear_on_run_start.strip().lower()

    if no_clear_flag or mode == "false":
        typer.echo(
            "[bffi-pipeline] Phase H pre-run Fuseki clear skipped "
            "(--no-clear-fuseki or BFFI_FUSEKI_CLEAR_ON_RUN_START=false).",
            err=True,
        )
        return

    result = clear_run_output_graphs(
        fuseki_url=fuseki_url,
        graph_base=graph_base,
        max_triples_per_graph=settings.fuseki_clear_max_triples,
        force=force_clear_flag,
        client=client,
    )

    if not result.fuseki_reachable and mode == "strict":
        typer.echo(
            f"[bffi-pipeline] Fuseki unreachable at {fuseki_url} and "
            "BFFI_FUSEKI_CLEAR_ON_RUN_START=strict — refusing to proceed.",
            err=True,
        )
        raise typer.Exit(code=1)

    # Best-effort: write the outcome to the run manifest. No-op when
    # the manifest doesn't exist (BFFI_OBSERVABILITY_SIDECAR=none).
    manifest_path = settings.data_dir / MANIFEST_FILENAME
    update_manifest_field(manifest_path, pre_run_fuseki_clear=result.to_manifest_dict())


@app.command("load-finto")
def load_finto_command(
    output_dir: Annotated[
        Path | None,
        typer.Option(
            "--output-dir",
            help=(
                "Where Finto dump TTLs are cached; defaults to <BFFI_DATA_DIR>. "
                "The actual files land under <output-dir>/finto-dumps/."
            ),
            file_okay=False,
            dir_okay=True,
            resolve_path=True,
        ),
    ] = None,
    fuseki_url: Annotated[
        str | None,
        typer.Option(
            "--fuseki-url",
            help="Fuseki dataset endpoint; defaults to FUSEKI_URL from settings.",
        ),
    ] = None,
    max_age_days: Annotated[
        int,
        typer.Option(
            "--max-age-days",
            help="Re-download a cached dump only if its mtime is older than this many days.",
        ),
    ] = 30,
    force: Annotated[
        bool,
        typer.Option(
            "--force",
            help="Re-download every dump regardless of cache freshness.",
        ),
    ] = False,
    fold_pref_labels: Annotated[
        bool,
        typer.Option(
            "--fold-pref-labels/--no-fold-pref-labels",
            help=(
                "Materialise bffi:foldedLabel triples on every "
                "skos:prefLabel and skos:altLabel of every concept in the "
                "downloaded dump (P-10 Phase C.1). Default OFF — the "
                "2026-05-13 Phase C bench attempt found this doubled "
                "Phase 1 SPARQL traffic without an offsetting reduction "
                "in tier-2 picker calls on the May 12 corpus. Using the "
                "tier-0 expansion path requires BOTH this flag and the "
                "resolver-side BFFI_M9_TIER0_EXPANSION=1; the materialised "
                "triples are inert otherwise. See "
                "docs/performance/2026-05-13-5k-m2-max-phase-c-attempt.md."
            ),
        ),
    ] = False,
) -> None:
    """Refresh the KANTO/YSO/KAUNO/MUSO/SLM named graphs in Fuseki.

    Downloads the canonical Turtle dumps from api.finto.fi and PUTs each
    into its named graph via SPARQL Graph Store Protocol. Skosmos's
    per-vocab entries in `config/skosmos-config.ttl` point at the same
    graph URIs, so labels light up on the next concept-page render.
    """
    settings = get_settings()
    auth: tuple[str, str] | None = (
        (settings.fuseki_user, settings.fuseki_password)
        if settings.fuseki_user and settings.fuseki_password
        else None
    )
    with httpx.Client(
        timeout=httpx.Timeout(60.0, read=300.0),
        follow_redirects=True,
        headers={"User-Agent": load_finto.DEFAULT_USER_AGENT},
        auth=auth,
    ) as client:
        summary = load_finto.run(
            output_dir=output_dir,
            fuseki_url=fuseki_url,
            max_age_days=max_age_days,
            force=force,
            http_client=client,
            fold_pref_labels=fold_pref_labels,
        )
    typer.echo(summary.render())


@app.command("lookup-helmet")
def lookup_helmet_command(
    helmet_id: Annotated[
        str,
        typer.Argument(
            help="The Helmet bibliographic record ID to look up.",
        ),
    ],
    fuseki_url: Annotated[
        str | None,
        typer.Option(
            "--fuseki-url",
            help="Fuseki dataset endpoint; defaults to FUSEKI_URL from settings.",
        ),
    ] = None,
) -> None:
    """Resolve a Helmet bib ID to its canonical Work + Expressions (M10)."""
    target_url = fuseki_url or get_settings().fuseki_url
    with httpx.Client(timeout=30.0) as client:
        rows = load.lookup_helmet_id(client, helmet_id, fuseki_url=target_url)
    typer.echo(load.render_helmet_lookup(rows))


# --- bffi-pipeline provenance ... -----------------------------------------


def _parse_age_spec(spec: str) -> int:
    """Parse a duration like ``"90d"`` / ``"30d"`` / a bare number into days."""
    text = spec.strip().lower()
    if not text:
        raise typer.BadParameter("--older-than must be a duration like '90d'.")
    if text.endswith("d"):
        text = text[:-1]
    try:
        days = int(text)
    except ValueError as exc:
        raise typer.BadParameter(
            f"--older-than {spec!r} is not a recognised duration; use '90d' or a bare integer."
        ) from exc
    if days < 0:
        raise typer.BadParameter("--older-than must be non-negative.")
    return days


@provenance_app.command("compact")
def provenance_compact_command(
    older_than: Annotated[
        str,
        typer.Option(
            "--older-than",
            help="Strip rawResponse from Activities older than this; e.g. '90d'.",
        ),
    ] = f"{prov_writer.COMPACTION_AGE_DAYS}d",
    provenance_path: Annotated[
        Path | None,
        typer.Option(
            "--path",
            help="Path to provenance.ttl; defaults to <BFFI_DATA_DIR>/provenance.ttl.",
            file_okay=True,
            dir_okay=False,
            resolve_path=True,
        ),
    ] = None,
) -> None:
    """Strip stale rawResponse literals and refresh lastCompactedAt (M7)."""
    days = _parse_age_spec(older_than)
    removed = prov_writer.compact_provenance(
        older_than_days=days,
        provenance_path=provenance_path,
    )
    typer.echo(
        f"compaction complete: removed {removed} bffi-prov:rawResponse literal(s) "
        f"older than {days}d"
    )


if __name__ == "__main__":
    app()
