"""M6 — Cascade LLM judge stage.

Public surface is re-exported from :mod:`bffi_pipeline.stages.m6.runner`.
Private helpers (anything prefixed with ``_``) stay reachable via the
submodule path (``from bffi_pipeline.stages.m6.runner import _foo``).
"""

from bffi_pipeline.stages.m6.runner import (
    CHECKPOINT_INTERVAL,
    CHECKPOINT_SUFFIX,
    CONNECTION_BACKOFF_SECONDS,
    DECISIONS_FILENAME,
    DEFAULT_CONCURRENCY,
    FALLBACK_CONFIDENCE_THRESHOLD,
    MAX_CONNECTION_RETRIES,
    MAX_VALIDATION_RETRIES,
    MIN_RATIONALE_CHARS,
    STAGE_AUTO_MERGE,
    STAGE_PRIMARY,
    STAGE_SECOND_OPINION,
    STAGE_WATCHDOG,
    CascadeStep,
    JudgeBatchProgress,
    JudgeBatchResult,
    JudgeCache,
    JudgeCheckpoint,
    JudgeOutcome,
    WorkMatchDecision,
    WorkMatchDecisionFast,
    WorkRecord,
    cascade_judge,
    default_cache_path,
    extract_work_records,
    judge_batch,
    judge_pair,
    prompt_hash,
    prompt_hash_fast,
    prompt_text,
    prompt_text_fast,
    synthesize_auto_merge_outcome,
)

__all__ = [
    "CHECKPOINT_INTERVAL",
    "CHECKPOINT_SUFFIX",
    "CONNECTION_BACKOFF_SECONDS",
    "DECISIONS_FILENAME",
    "DEFAULT_CONCURRENCY",
    "FALLBACK_CONFIDENCE_THRESHOLD",
    "MAX_CONNECTION_RETRIES",
    "MAX_VALIDATION_RETRIES",
    "MIN_RATIONALE_CHARS",
    "STAGE_AUTO_MERGE",
    "STAGE_PRIMARY",
    "STAGE_SECOND_OPINION",
    "STAGE_WATCHDOG",
    "CascadeStep",
    "JudgeBatchProgress",
    "JudgeBatchResult",
    "JudgeCache",
    "JudgeCheckpoint",
    "JudgeOutcome",
    "WorkMatchDecision",
    "WorkMatchDecisionFast",
    "WorkRecord",
    "cascade_judge",
    "default_cache_path",
    "extract_work_records",
    "judge_batch",
    "judge_pair",
    "prompt_hash",
    "prompt_hash_fast",
    "prompt_text",
    "prompt_text_fast",
    "synthesize_auto_merge_outcome",
]
